include: package:effective_dart/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
  - camel_case_types

analyzer:
  errors:
    public_member_api_docs: ignore
    omit_local_variable_types: ignore
    missing_return: error
#   exclude:
#     - path/to/excluded/files/**