String statJson = '''
{
    "gameVersionId": 136,
    "enabled": true,
    "heroUnlockOrder": 1.0,
    "team": true,
    "cmEnabled": true,
    "newPlayerEnabled": true,
    "attackType": "Melee",
    "startingArmor": 2.36,
    "startingMagicArmor": 25.0,
    "startingDamageMin": 29.0,
    "startingDamageMax": 33.0,
    "attackRate": 1.4,
    "attackAnimationPoint": 0.3,
    "attackAcquisitionRange": 600.0,
    "attackRange": 150.0,
    "primaryAttribute": "agi",
    "heroPrimaryAttribute": 1,
    "strengthBase": 23.0,
    "strengthGain": 1.3,
    "intelligenceBase": 12.0,
    "intelligenceGain": 1.8,
    "agilityBase": 24.0,
    "agilityGain": 2.8,
    "hpRegen": 0.25,
    "mpRegen": 0.0,
    "moveSpeed": 310.0,
    "moveTurnRate": 0.5,
    "hpBarOffset": 0.0,
    "visionDaytimeRange": 1800.0,
    "visionNighttimeRange": 800.0,
    "complexity": 1
}
''';
